### ISSUE TITLE
Learning outcomes and course details page

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/write-javascript-actions#1]
I know this is obvious, but opening up an issue so we can divide-and-conquer when it's time to push this course through to completion. The course needs a `course-details.yml` file with the learning outcomes. We might also consider adding [enhanced metadata](https://github.com/github/learning-engineering/issues/715) to this course since it's new and we can start off testing it on the right foot.

**Comment by brianamarie** [comment]
Closing this issue, because this course does have the proper `course-details.yml` file.
