### ISSUE TITLE
Sample code uses outdated @action/toolkit API

### ISSUE THREAD

**Issue by blaxx** [githubtraining/write-javascript-actions#17]
**Describe the bug**
Workflow action 'create-issue' fails even though, by course description, it should succeed.

**To Reproduce**
1. Follow the course until the end of the 'Add Third Actions JavaScript Files' step
2. Add a label to the current pull request
3. Check your actions tab: the workflow has failed with the error message: 'github.GitHub is not a constructor'

**Expected behavior**
By adding a label to my pull request I expect the workflow to finish successfully.

**Screenshots**
<img width="1552" alt="Bildschirmfoto 2020-06-20 um 22 52 06" src="https://user-images.githubusercontent.com/3218807/85211378-da514d80-b348-11ea-8425-1905b18f7ac2.png">
<img width="1552" alt="Bildschirmfoto 2020-06-20 um 22 46 02" src="https://user-images.githubusercontent.com/3218807/85211387-f05f0e00-b348-11ea-8f99-935a48d92547.png">

**Additional context**
Seems like the way the octokit client is created in the sample code is no longer supported by  @actions/toolkit v3, also see  [this pull request](https://github.com/actions/toolkit/pull/453).

**Comment by mattdavis0351** [comment]
@blaxx @zhiliangxu Thank you for your contributions to this course.  I'll address this issue, and the associate pull requests today 😄
